### ISSUE TITLE
Loading state when fetching recommendations

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol-operations#103]
Right now the message "No video corresponds to your research criterias" when I refresh the page and before recommendations are fetched. This message should only appear when we receive the list of videos and the list is empty.

A good thing to display durring fetching of the list of videos can be found there: https://material-ui.com/components/progress/#progress

**Comment by sandre35** [comment]
The current issue is that there is one temporary state at the start of the component cycle life. 
This temporary state is the one given as default in the argument `useState`
![Screenshot from 2021-09-14 17-23-34](https://user-images.githubusercontent.com/65041823/133286749-5146029e-24f3-482d-abdc-2998644d1766.png)
