### ISSUE TITLE
Paper on ArXiV

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol-operations#11]
We need to upload a paper on ArXiV describing Tournesol overall, so that we can be more easily cited by academic papers (like my upcoming papers 😜).

I'll work on a first draft to upload quickly soon.

(the advantage of ArXiV is that we can be easily cited, while regularly updating the paper)

**Comment by sergeivolodin** [comment]
@lenhoanglnh added my thoughts on the abstract -- I think it's great, but there are some hard-to-understand sentences. See Overleaf.

![image](https://user-images.githubusercontent.com/1012270/118838054-a74f6b00-b8c5-11eb-8476-fb1fbf36fd47.png)

Which other sections deserve the most attention?

**Comment by sergeivolodin** [comment]
@lenhoanglnh added some comments to intro and conclusion as well

**Comment by lenhoanglnh** [comment]
Finally it got accepted to ArXiV!
https://arxiv.org/abs/2107.07334

I'll wait for the 2022 call for paper to email all the authors, but I suggest we update it and submit it to (FAccT)[https://facctconference.org/] in the end of September.
