### ISSUE TITLE
Adapt Nginx recipe to use gunicorn

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol-operations#19]
Using the boilerplate backend django application, ensure that our ansible infra serves the application.

This might be best reviewed by @elineda

**Comment by jstainer-kleis** [comment]
Still using unix socket for nginx->gunicorn requests and not handling database migration / static assets copy / superuser creation (commands in the README to do that manually though).

The last bits may be better addressed by a CI/CD pipeline. Still unsure about unix socket vs. TCP for nginx->gunicorn requests.
