### ISSUE TITLE
Develop a strategy in case if server is insufficient (OOM/CPU load)

### ISSUE THREAD

**Issue by sergeivolodin** [tournesol-app/tournesol-operations#2]
1. Set a timeout on apache, in case if exceeded, show a message like "tournesol is experiencing difficulties, please stand by and try again later etc"
    - [ ] Write the message and the layout @tournesol-app/designers 
2. Create monitoring for OOM in case if Munin is not working (or report right after OOM ends)
![image](https://user-images.githubusercontent.com/1012270/116136004-16281280-a6d2-11eb-9ff1-3bebaeeba155.png)

On the figure, Munin is not running because OOM, therefore, there are reports on Telegram
3. Buy a new server and migrate to it (database, website, ...). Freeze the DB for some time (showing "technical difficulties"), copy and run on the new instance. Set up a tunnel for apache traffic to go there before DNS changes

**Comment by TheDuckWhisperer** [comment]
Designs can be viewed in Figma through this link: 
https://www.figma.com/file/3uI7FiBhXp0hhgdTdHBSkj/Tournesol?node-id=479%3A36
You need to make a free Figma account to inspect elements and to download the assets.

Discussion and context for the designs can be found on the Discord channel #interface.

This video explains how to inspect a Figma file and how to download assets for development. 
https://youtu.be/B242nuM3y2s?t=50

**Comment by sergeivolodin** [comment]
There are some public details about YT: https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/45530.pdf

**Comment by sergeivolodin** [comment]
@TheDuckWhisperer @lenhoanglnh the server has daily spikes in API response time -- we might want to look into this issue a bit sooner :)

![image](https://user-images.githubusercontent.com/1012270/118998543-0de19100-b979-11eb-94be-823afbcc7ae1.png)

![image](https://user-images.githubusercontent.com/1012270/118998413-f60a0d00-b978-11eb-9158-7f6b27d69f16.png)

https://munin.tournesol.app/app/tournesol.app/ts_api.html

**Comment by sergeivolodin** [comment]
Training on a GPU can be a potential way to speed things up once we have more data: https://github.com/tournesol-app/tournesol/issues/134
