### ISSUE TITLE
Add all admin users on ansible recipe

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol-operations#21]

**Comment by jstainer-kleis** [comment]
jst, lpfaucon, sergei and lenhoang already added.

For additional admins, they should be added in this file:
https://github.com/tournesol-app/tournesol-infra/blob/master/ansible/group_vars/tournesol.yml

and a directory with their dotfiles (especially `.ssh/authorized_keys`) should be created there:
https://github.com/tournesol-app/tournesol-infra/tree/master/ansible/roles/users/files/admin-users

then running the playbook should do the job.
