### ISSUE TITLE
Identify minimal API

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol-operations#26]

**Comment by sergeivolodin** [comment]
maybe just keep ratings, search, statistics? we comment out comments, rate later (we implement rate later in the extension maybe -- less data to collect), video sampling (also let's do it on the extension side -- now I agree), we maybe disable user info and replace it with a placeholder "user information will be available soon" -- when we are sure it's fine to turn on?

@lfaucon

**Comment by lfaucon** [comment]
Yes, this is the idea. There are still a lot of details. I will draw a diagram of everything that should be included and should work. Thanks for the comment!

**Comment by AlbericC** [comment]
>we maybe disable user info and replace it with a placeholder "user information will be available soon" -- when we are sure it's fine to turn on?

I was having the same kind of thinking : an external "no-nonsense" user API, for the app to work, without any detail in the "get", along with a "private/protected" user data API for internal use only (not exposed to the outside world) if necessary for research.

**Comment by lfaucon** [comment]
I recommend focusing on these features at first: 
- [x] User creation, password reset, authentication (implemented on frontend, mobile and extension)
- [ ] Creating, updating, fetching, listing comparisons
- [ ] ML algorithms running daily
- [ ] Video information is computed (YouTube-dl & tournesol information, … more TBD)
- [ ] Users can fetch video information including information from YouTube (views, duration, likes, … more TBD) and from Tournesol (scores per criteria, aggregated score, number of comparisons and number of contributors, … more TBD)
- [ ] Adding, deleting, fetching from Rate Later list
- [ ] Retrieving search results: sorting by fixed Tournesol scores, dates, language (optional: search phrase, criteria preferences)
