### ISSUE TITLE
Recruit EPFL's research engineer

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol-operations#30]

**Comment by lenhoanglnh** [comment]
The job offers are now online (there's a bonus, with also a postdoc opening!).

1. An experienced Django dev engineer.
https://recruiting.epfl.ch/Vacancies/1855/Description/2
2. A postdoc for ML implementations.
https://recruiting.epfl.ch/Vacancies/1856/Description/2

Next step: Make a video next Monday to reach out to more potential applicants 😋
