### ISSUE TITLE
Clearly define Sergei's responsibilities

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol-operations#38]
Create a short document aggreed on by @lenhoanglnh @sergeivolodin @aidanjungo and @lfaucon describing Sergei's role

**Comment by lenhoanglnh** [comment]
I've created this document. It is somewhat similar to the Django dev job offer I've written through EPFL.
https://docs.google.com/document/d/1jS1HkURMwp1CCELHbKn9yAQ2TU-39-an0wVPBxS565A/edit

**Comment by lfaucon** [comment]
I have updated the document.

**Comment by sergeivolodin** [comment]
Added a draft for the rights (and maybe a code of conduct)
