### ISSUE TITLE
Transfer tournesol domain's to association's GoDaddy account

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol-operations#39]
1. Create an account on Godaddy with the association's email. 
2. Coordinate with Sergei to transfer the tournesol.app domain to the new account

**Comment by lenhoanglnh** [comment]
I've created the account, and asked Sergei to transfer the domain.

**Comment by lenhoanglnh** [comment]
Sergei has transferred the domain to tournesol.application@gmail.com.
@lfaucon, you should have received an email to access the GoDaddy domain through your GoDaddy account.
