### ISSUE TITLE
Distributions of Youtube video metadata

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol-operations#46]
Figure out whether we can:
- distribute scripts using youtube-dl on Github
- distribute files/db dumps containing youtube video metadata on Github
- distribute video's metadata on tournesol.app

**Comment by lfaucon** [comment]
Could get good advice from Mahdi or Manoel

**Comment by lenhoanglnh** [comment]
We go without metadata for now for what's distributed, to maximize the chance of a collaboration with Google.
Only video ids appear in the distributed db.

**Comment by lfaucon** [comment]
Do you confirm that this applies to video titles on the website? If not can you give a more detailed decision?

**Comment by lenhoanglnh** [comment]
To be more precise:
- For the distribution, do not share any metadata. Only video ids appear.
- For the website, we use the relevant metadata (id, title, release_date, channel_id, duration, view_count).
