### ISSUE TITLE
Set up REST operations for user's rate later list

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol-operations#52]
Tournesol contributors should be able to manipulate their rate later list: The need to add, fetch, list, or delete from their rate later list using the api endpoint /rate_later

**Comment by GresilleSiffle** [comment]
Hello @lfaucon 

Few questions about this issue. I hope they will help to clarify the scope of it.

**1** Which `Video` fields should be included in this endpoint? Serializing the `VideoRateLater` model requires to serialize also the related `Video` model, and a lot of fields are available.

**2** I understand the use case of adding, listing and deleting a video from a user's rate later list, but I don't see the use case addressed by the fetch action. A user fetching a video from its rate later list is the same as just fetching a video from the `Video` table given an identifier? 

- if yes, I think the fetch action should be bound to a more generic endpoint like `/video/{id}/` or similar, and can be done in a different issue to reduce the scope of this one
- if no, the fetch action should be bound to the desired `/rate_later` endpoint

**3** concerning the endpoint `rate_later`, it might be a good idea to use a namespace in the URL to regroup all endpoints related to the logged user, as opposed to the public API which is available to anyone.

example
```http
# return the video in the logged user's rate later list
GET /api/user/videoratelater
# or
GET /api/logged/videoratelater

# return all profile data of the logged user
GET /api/user/profile
# or
GET /api/logged/profile
```
For me, it allows a better struture of the API, a cleaner URL design, and it emphasis a semantic approach of the URL. By sending a request on `/api/user/videoratelater` we know we access the rate later list of a user, and not THE rate later list of the tournesol project which doesn't make sense at the time of writing. Also there is no variable part in my examples URL like in `/api/user/{id}`, it's a hint telling us that the target user is the logged user. 

In the `JSON:API` specification, there are recommandations on how to structure URL:
https://jsonapi.org/recommendations/#urls-relationships

Note that the true `JSON:API` specification focus, is the JSON structure appearing in HTTPresponses, and not the URL design of the API, but I think their recommendations are pertinent.  

What do you think @lfaucon? What do you think @elineda? : )
