### ISSUE TITLE
License our code

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol-operations#82]

**Comment by lfaucon** [comment]
Following discussions on Friday August 6, we decided to use the AGPL license for our codebase.

We need further research to decide on a different more permissive license for our Tournesol's data.

**Comment by lenhoanglnh** [comment]
We had this discussion on license: https://github.com/tournesol-app/tournesol-backend/issues/23
With this link (in French) about data licenses: https://fr.wikipedia.org/wiki/Donn%C3%A9es_ouvertes#Licences_open_data

I think that "Open Database Commons" is a suitable license for the Tournesol database (rights to use, copy, modify, redistribute, modify, and produce work based on the database, if the original database author is provided).

By opposition, "Open Data Commons Open Database License" (ODbL) seems too demanding, as it requires any object derived from our database to be distributed with the same license. I fear that this will hinder its re-use by all sorts of companies that may want to make their algorithms more ethical, not only Google, but also companies who train neural nets (like language models) and auditing companies that may want to leverage our data to audit recommendation algorithms.

**Comment by lfaucon** [comment]
Added licenses to frontend, backend and infra repositories.

Will create an additional ticket for the database license. I believe this license file will probably need to be included in the downloadable dump of the public database once we re-introduce this feature.
