### ISSUE TITLE
Backend video metadata

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol-operations#91]
- Use YoutubeApi to access video title, channel, date, and duration (additional optional information: number of likes and views)
- When a video is added, start an asynchronous process that fetches the metadata and adds writes it on the Video model in the database (only if the video had not been added previously)
- Verify that API use allows to store and redistriburte what is obtained from the API.

**Comment by sandre35** [comment]
I have not read any conditions that constrain us for storage or redistribution: 
https://developers.google.com/youtube/terms/api-services-terms-of-service-emea-fr#security
If someone can also confirm that?

**Comment by aidanjungo** [comment]
I don't see any neither, but I think one of the risk is that one day, if for any reason they don't like what we are doing, they could use "YouTube reserves the right to (i) suspend or terminate access to, or use of, any aspects of the YouTube API Services by you, your API Client(s) and those acting on your behalf" to close our access.

**Comment by lfaucon** [comment]
Ok, if "being suspended from usage" is our only risk, let's go ahead! Thanks for double-checking @aidanjungo

**Comment by jstainer-kleis** [comment]
I'd say that checking how the terms and conditions impact our planned usage is a perfect task for the PM that is about to join us and who's way of contributing didn't sound exactly well defined.
